# Generated by Django 4.1.1 on 2022-09-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(max_length=120)),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('description', models.TextField(default='Description du produit')),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
