# Generated by Django 4.1.1 on 2022-09-14 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_category_produit_slug_produit_thumbnail_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Categorie',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='category',
            new_name='categorie',
        ),
    ]
