# Generated by Django 4.1.1 on 2022-09-15 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_rename_category_categorie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True)),
                ('localisation', models.URLField(null=True)),
                ('telephone', models.TextField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commercant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, null=True, unique=True)),
                ('localisation', models.URLField(null=True)),
                ('telephone', models.TextField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='disponbile',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='titre',
            field=models.TextField(max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('contacted', models.BooleanField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.client')),
                ('produit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Store.produit')),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='commercant',
            field=models.ManyToManyField(blank=True, related_name='produitachete', to='Store.commercant'),
        ),
    ]
