# Generated by Django 4.1.1 on 2022-09-15 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_client_commercant_produit_disponbile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='produit',
            name='created_atp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
