# Generated by Django 4.1.1 on 2022-09-27 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_produit_options_produit_created_atp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produit',
            name='created_atp',
        ),
    ]
