# Generated by Django 4.1.1 on 2022-09-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_remove_produit_created_atp'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='created_atp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
