# Generated by Django 4.1.1 on 2022-10-17 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_produit_created_atp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produit',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='created_atp',
            new_name='date_added',
        ),
    ]
