# Generated by Django 4.1.1 on 2022-10-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_produit_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField(max_length=9)),
                ('adresse', models.CharField(max_length=200)),
                ('ville', models.CharField(max_length=60)),
                ('pays', models.CharField(max_length=60)),
                ('codepostal', models.CharField(max_length=5)),
                ('date_commande', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-date_commande'],
            },
        ),
    ]
