# Generated by Django 4.1.1 on 2022-10-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_commande'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='total',
            field=models.CharField(default=500, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commande',
            name='codepostal',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
